// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Models;

#nullable disable

namespace ControleDePagamentos.Migrations
{
    [DbContext(typeof(AppDataContext))]
    [Migration("20240429012348_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("Models.Contato", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Observacoes")
                        .HasColumnType("TEXT");

                    b.Property<int>("PessoaID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefone")
                        .HasColumnType("TEXT");

                    b.Property<string>("WhatsApp")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("PessoaID");

                    b.ToTable("Contato");
                });

            modelBuilder.Entity("Models.Endereco", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CEP")
                        .HasColumnType("TEXT");

                    b.Property<string>("Cidade")
                        .HasColumnType("TEXT");

                    b.Property<string>("EnderecoCompleto")
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .HasColumnType("TEXT");

                    b.Property<int>("PessoaID")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.HasIndex("PessoaID");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("Models.Pagamento", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CredorID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataDePagamento")
                        .HasColumnType("TEXT");

                    b.Property<int>("DevedorID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Valor")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("CredorID");

                    b.HasIndex("DevedorID");

                    b.ToTable("Pagamentos");
                });

            modelBuilder.Entity("Models.Pedido", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CredorID")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataDoPedido")
                        .HasColumnType("TEXT");

                    b.Property<int>("DevedorID")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("ValorTotal")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("CredorID");

                    b.HasIndex("DevedorID");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Models.Pessoa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("Documento")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.HasKey("ID");

                    b.ToTable("Pessoas");
                });

            modelBuilder.Entity("Models.Contato", b =>
                {
                    b.HasOne("Models.Pessoa", "Pessoa")
                        .WithMany("Contatos")
                        .HasForeignKey("PessoaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Models.Endereco", b =>
                {
                    b.HasOne("Models.Pessoa", "Pessoa")
                        .WithMany("Enderecos")
                        .HasForeignKey("PessoaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("Models.Pagamento", b =>
                {
                    b.HasOne("Models.Pessoa", "Credor")
                        .WithMany()
                        .HasForeignKey("CredorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Pessoa", "Devedor")
                        .WithMany()
                        .HasForeignKey("DevedorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credor");

                    b.Navigation("Devedor");
                });

            modelBuilder.Entity("Models.Pedido", b =>
                {
                    b.HasOne("Models.Pessoa", "Credor")
                        .WithMany()
                        .HasForeignKey("CredorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models.Pessoa", "Devedor")
                        .WithMany()
                        .HasForeignKey("DevedorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Credor");

                    b.Navigation("Devedor");
                });

            modelBuilder.Entity("Models.Pessoa", b =>
                {
                    b.Navigation("Contatos");

                    b.Navigation("Enderecos");
                });
#pragma warning restore 612, 618
        }
    }
}
