

@ControleDePagamentos_HostAddress = http://localhost:5241

//Obtem todas pessoas cadastradas
GET {{ControleDePagamentos_HostAddress}}/api/pessoas/exibir


###

//Busca pessoa por ID
GET {{ControleDePagamentos_HostAddress}}/api/pessoas/exibir/id/1


###

//Busca pessoa por nome
GET {{ControleDePagamentos_HostAddress}}/api/pessoas/exibir/nome/Ana


###

//Cadastro de pessoas
POST {{ControleDePagamentos_HostAddress}}/api/pessoas/cadastrar
Content-Type: application/json

[
    {
        "ID": 1,
        "Nome": "João",
        "NumDocumento": "123456789",
        "Tipo": 0,
        "Enderecos": [
            {
                "ID": 1,
                "Logradouro": "Rua das Flores",
                "Bairro": "Centro",
                "Cidade": "Curitiba",
                "Estado": "PR",
                "CEP": "80000-000",
                "PessoaID": 1
            }
        ],
        "Contatos": [
            {
                "ID": 1,
                "Email": "joao@email.com",
                "WhatsApp": "+55 41 99999-9999",
                "Telefone": "+55 41 88888-8888",
                "Observacoes": "Contato principal",
                "PessoaID": 1
            }
        ]
    },
    {
        "ID": 2,
        "Nome": "Maria",
        "NumDocumento": "987654321",
        "Tipo": 1,
        "Enderecos": [
            {
                "ID": 2,
                "Logradouro": "Avenida das Américas",
                "Bairro": "Jardim Botânico",
                "Cidade": "Curitiba",
                "Estado": "PR",
                "CEP": "81000-000",
                "PessoaID": 2
            }
        ],
        "Contatos": [
            {
                "ID": 2,
                "Email": "maria@email.com",
                "WhatsApp": "+55 41 77777-7777",
                "Telefone": "+55 41 66666-6666",
                "Observacoes": "Contato principal",
                "PessoaID": 2
            }
        ]
    },
    {
        "ID": 3,
        "Nome": "Carlos",
        "NumDocumento": "111222333",
        "Tipo": 0,
        "Enderecos": [
            {
                "ID": 3,
                "Logradouro": "Rua das Orquídeas",
                "Bairro": "Jardim das Flores",
                "Cidade": "Curitiba",
                "Estado": "PR",
                "CEP": "81000-001",
                "PessoaID": 3
            }
        ],
        "Contatos": [
            {
                "ID": 3,
                "Email": "carlos@email.com",
                "WhatsApp": "+55 41 55555-5555",
                "Telefone": "+55 41 44444-4444",
                "Observacoes": "Contato principal",
                "PessoaID": 3
            }
        ]
    },
    {
        "ID": 4,
        "Nome": "Ana",
        "NumDocumento": "444555666",
        "Tipo": 1,
        "Enderecos": [
            {
                "ID": 4,
                "Logradouro": "Avenida das Rosas",
                "Bairro": "Jardim das Rosas",
                "Cidade": "Curitiba",
                "Estado": "PR",
                "CEP": "81000-002",
                "PessoaID": 4
            }
        ],
        "Contatos": [
            {
                "ID": 4,
                "Email": "ana@email.com",
                "WhatsApp": "+55 41 33333-3333",
                "Telefone": "+55 41 22222-2222",
                "Observacoes": "Contato principal",
                "PessoaID": 4
            }
        ]
    },
    {
        "ID": 5,
        "Nome": "Pedro",
        "NumDocumento": "777888999",
        "Tipo": 0,
        "Enderecos": [
            {
                "ID": 5,
                "Logradouro": "Rua das Margaridas",
                "Bairro": "Jardim das Margaridas",
                "Cidade": "Curitiba",
                "Estado": "PR",
                "CEP": "81000-003",
                "PessoaID": 5
            }
        ],
        "Contatos": [
            {
                "ID": 5,
                "Email": "pedro@email.com",
                "WhatsApp": "+55 41 11111-1111",
                "Telefone": "+55 41 00000-0000",
                "Observacoes": "Contato principal",
                "PessoaID": 5
            }
        ]
    },
    {
        "ID": 6,
        "Nome": "Julia",
        "NumDocumento": "000111222",
        "Tipo": 1,
        "Enderecos": [
            {
                "ID": 6,
                "Logradouro": "Avenida das Tulipas",
                "Bairro": "Jardim das Tulipas",
                "Cidade": "Curitiba",
                "Estado": "PR",
                "CEP": "81000-004",
                "PessoaID": 6
            }
        ],
        "Contatos": [
            {
                "ID": 6,
                "Email": "julia@email.com",
                "WhatsApp": "+55 41 99999-0000",
                "Telefone": "+55 41 88888-1111",
                "Observacoes": "Contato principal",
                "PessoaID": 6
            }
        ]
    },
    {
        "ID": 7,
        "Nome": "Lucas",
        "NumDocumento": "333444555",
        "Tipo": 0,
        "Enderecos": [
            {
                "ID": 7,
                "Logradouro": "Rua das Violetas",
                "Bairro": "Jardim das Violetas",
                "Cidade": "Curitiba",
                "Estado": "PR",
                "CEP": "81000-005",
                "PessoaID": 7
            }
        ],
        "Contatos": [
            {
                "ID": 7,
                "Email": "lucas@email.com",
                "WhatsApp": "+55 41 77777-2222",
                "Telefone": "+55 41 66666-3333",
                "Observacoes": "Contato principal",
                "PessoaID": 7
            }
        ]
    }
]


###
POST {{ControleDePagamentos_HostAddress}}/api/pessoas/cadastrar
Content-Type: application/json

[
    {
        "ID": 8,
        "Nome": "Sebastião e Breno Construtora Ltda",
        "NumDocumento": "73.406.160/0001-09",
        "Tipo": 1,
        "Enderecos": [
            {
                "ID": 8,
                "Logradouro": "Travessa Abel",
                "Bairro": "São João do Cabrito",
                "Cidade": "Salvador",
                "Estado": "BA",
                "CEP": "40490-380",
                "PessoaID": 8
            }
        ],
        "Contatos": [
            {
                "ID": 8,
                "Email": "qualidade@sebastiaoebrenoconstrutora.com.br",
                "WhatsApp": "+55 71 3778-9490",
                "Telefone": "+55 71 98258-0684",
                "Observacoes": "Contato Administrativo",
                "PessoaID": 8
            }
        ]
    },
        {
        "ID": 9,
        "Nome": "Ricardo e Regina Marketing Ltda",
        "NumDocumento": "16.586.509/0001-06",
        "Tipo": 1,
        "Enderecos": [
            {
                "ID": 9,
                "Logradouro": "Rua das Macieiras, 950",
                "Bairro": "Alphaville Graciosa",
                "Cidade": "Pinhais",
                "Estado": "PR",
                "CEP": "83327-200",
                "PessoaID": 9
            }
        ],
        "Contatos": [
            {
                "ID": 9,
                "Email": "orcamento@ricardoereginamarketingltda.com.br",
                "WhatsApp": "+55 41 2625-8597",
                "Telefone": "+55 41 98830-3428",
                "Observacoes": "Contato Comercial",
                "PessoaID": 9
            }
        ]
    },
            {
        "ID": 10,
        "Nome": "Alice e Victor Buffet Ltda",
        "NumDocumento": "16.586.509/0001-06",
        "Tipo": 1,
        "Enderecos": [
            {
                "ID": 10,
                "Logradouro": "Rua Javert Czarnecki Mizerkowski, 10",
                "Bairro": "Guatupê",
                "Cidade": "São José dos Pinhais",
                "Estado": "PR",
                "CEP": "83060-205",
                "PessoaID": 10
            }
        ],
        "Contatos": [
            {
                "ID": 10,
                "Email": "sac@aliceevictorbuffetltda.com.br",
                "WhatsApp": "+55 41 98778-1912",
                "Telefone": "+55 41 98778-1912",
                "Observacoes": "Contato Principal",
                "PessoaID": 10
            }
        ]
    }
]


###
//Atualizar uma pessoa
PUT {{ControleDePagamentos_HostAddress}}/api/pessoas/alterar/5
Content-Type: application/json

{
   "nome":"Fernando Soares",
   "numDocumento":"1234567890",
   "tipo":0,
   "enderecos":[
      {
         "id":5,
         "Logradouro":"Rua das Violetas",
         "Bairro":"Jardim das Violetas",
         "Cidade":"Curitiba",
         "Estado":"PR",
         "CEP":"81000-005",
         "PessoaID":5
      }
   ],
   "contatos":[
      {
         "id":5,
         "email":"pedrosoares@teste.com",
         "whatsapp":"551234567890",
         "telefone":"1234-5678"
      }
   ]
}

###
//Remover uma pessoa
DELETE {{ControleDePagamentos_HostAddress}}/api/pessoas/deletar/7


###

//Cadastro de pedido
POST {{ControleDePagamentos_HostAddress}}/api/pedido/cadastrar
Content-Type: application/json

[
    {
        "ID": 1,
        "ValorTotal": 100.50,
        "Nome": "Luminárias",
        "Descricao": "Kit Luminárias modernas",
        "DataDoPedido": "2024-05-06T00:00:00",
        "DataDoVencimento": "2024-05-20T00:00:00",
        "DevedorID": 1,
        "CredorID": 2
    },
    {
        "ID": 2,
        "ValorTotal": 200.00,
        "Nome": "Pedido 2",
        "Descricao": "Este é o pedido número 2",
        "DataDoPedido": "2024-05-07T00:00:00",
        "DataDoVencimento": "2024-05-21T00:00:00",
        "DevedorID": 3,
        "CredorID": 4
    },
    {
        "ID": 3,
        "ValorTotal": 300.75,
        "Nome": "Pedido 3",
        "Descricao": "Este é o pedido número 3",
        "DataDoPedido": "2024-05-08T00:00:00",
        "DataDoVencimento": "2024-05-22T00:00:00",
        "DevedorID": 5,
        "CredorID": 6
    }
]


###
//Cadastro de novos pedidos
POST {{ControleDePagamentos_HostAddress}}/api/pedido/cadastrar
Content-Type: application/json

[
    {
        "ID": 4,
        "ValorTotal": 1000,
        "Nome": "Luminárias",
        "Descricao": "Kit Luminárias Vintage",
        "DataDoPedido": "2024-05-06T00:00:00",
        "DataDoVencimento": "2024-06-06T00:00:00",
        "DevedorID": 9,
        "CredorID": 8
    },
    {
        "ID": 5,
        "ValorTotal": 2000.00,
        "Nome": "Cuba",
        "Descricao": "Cuba de Embutir Cerâmica Oval",
        "DataDoPedido": "2024-05-07T00:00:00",
        "DataDoVencimento": "2024-06-07T00:00:00",
        "DevedorID": 10,
        "CredorID": 8
    },
    {
        "ID": 6,
        "ValorTotal": 25000,
        "Nome": "Porcelanato",
        "Descricao": "Porcelanato Cimentício Acetinado Borda Reta Interno 61x61cm Beton 61988 Artens",
        "DataDoPedido": "2024-05-08T00:00:00",
        "DataDoVencimento": "2024-08-08T00:00:00",
        "DevedorID": 5,
        "CredorID": 8
    }
]

###
//Criar um novo pedido
POST {{ControleDePagamentos_HostAddress}}/api/pedido/cadastrar
Content-Type: application/json

[
    {
    "ID": 7,
        "valorTotal": 2099,
        "nome": "Smart TV",
        "descricao": "SAMSUNG Smart TV Crystal 50 4K UHD CU7700 - Alexa built in Samsung Gaming Hub, Preto",
        "dataDoPedido": "2024-05-01T00:00:00",
        "dataDoVencimento": "2024-05-10T00:00:00",
        "devedorID": 3,
        "credorID": 6
    }
]


###
//Obtem todos pedidos cadastradas
GET {{ControleDePagamentos_HostAddress}}/api/pedido/exibir


###
//altera um pedido
PUT {{ControleDePagamentos_HostAddress}}/api/pedido/alterar/2
Content-Type: application/json

{
  "id": 2,
  "valorTotal": 200.00,
  "nome": "Chuveiro",
  "descricao": "Chuveiro Elétrico Eletrônico 220V 7800w Preto Fosco Quadrado Acqua Duo Ultra Lorenzetti",
  "dataDoPedido": "2024-05-11T03:17:09.449Z",
  "dataDoVencimento": "2024-06-11T03:17:09.449Z",
  "status": "Aguarda pagamento",
  "devedorID": 3,
  "credorID": 8
}


###
//Remover um pedido
DELETE {{ControleDePagamentos_HostAddress}}/api/pedido/deletar/3


###
//Criar um novo pagamento
POST {{ControleDePagamentos_HostAddress}}/api/pagamento/cadastrar
Content-Type: application/json

{
  "Valor": 100.50,
  "DataDePagamento": "2024-05-10T00:00:00",
  "PedidoID": 1,
  "DevedorID": 1,
  "CredorID": 2
}


###
//Criar um novo pagamento
POST {{ControleDePagamentos_HostAddress}}/api/pagamento/cadastrar
Content-Type: application/json

{
  "Valor": 300.75,
  "DataDePagamento": "2024-05-22T00:00:00",
  "PedidoID": 2,
  "DevedorID": 5,
  "CredorID": 6
}


###
//Criar um novo pagamento
POST {{ControleDePagamentos_HostAddress}}/api/pagamento/cadastrar
Content-Type: application/json

{
  "Valor": 200.00,
  "DataDePagamento": "2024-05-21T00:00:00",
  "PedidoID": 3,
  "DevedorID": 5,
  "CredorID": 6
}

###
//Criar um novo pagamento
POST {{ControleDePagamentos_HostAddress}}/api/pagamento/cadastrar
Content-Type: application/json

{
  "valor": 1000,
  "dataDePagamento": "2024-05-25T00:00:00",
  "pedidoID": 4,
  "devedorID": 9,
  "credorID": 8
}

###
//Criar um novo pagamento
POST {{ControleDePagamentos_HostAddress}}/api/pagamento/cadastrar
Content-Type: application/json

{
  "valor": 2000,
  "dataDePagamento": "2024-05-30T00:00:00",
  "pedidoID": 5,
  "devedorID": 10,
  "credorID": 8
}


###
POST {{ControleDePagamentos_HostAddress}}/api/pagamento/cadastrar
Content-Type: application/json

{
  "valor": 25000,
  "dataDePagamento": "2024-06-15T00:00:00",
  "pedidoID": 6,
  "devedorID": 5,
  "credorID": 8
}

###
POST {{ControleDePagamentos_HostAddress}}/api/pagamento/cadastrar
Content-Type: application/json

{
  "valor": 2099,
  "dataDePagamento": "2024-05-08T00:00:00",
  "pedidoID": 7,
  "devedorID": 3,
  "credorID": 6
}

###

//terminar de incluir os testes
